### ISSUE TITLE
Doctype “rfc-anchor”?

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-rfcsubseries#3] opened 2021-12-26 00:55 UTC
Here’s an example:

https://github.com/ietf-ribose/relaton-data-rfcsubseries/blob/main/data/BCP0004.yaml#L11

Is this a valid type?

**Comment by ronaldtse** [comment] 2021-12-26 04:54
Not valid. @andrew2net can you help remove "rfc-anchor" as it is not a document identifier type?

**Comment by andrew2net** [comment] 2021-12-26 13:31
@ronaldtse not all documents form https://www.rfc-editor.org/refs/bibxml* have `reference[@anchor]` attribute. In this case the dcoument PubID is created from `reference[@docName]`, `reference[@number], or 'seriesInfo[@name="IETF"][@value]` attribute.
The problem is what we don't have information in the rleaton model whever the PubID was created from `anchor` or other source. When we rendering BibXML we need to know if `anchor` should be recreated from PubID.
Later `docidentifier[@scope]` was introduced. We can use the `scope` attribute to marking PubID when it created from `anchor` an recreate `anchor` attribute when rendereind BibXML. Is ok?

**Comment by strogonoff** [comment] 2021-12-28 09:06
Related: https://github.com/relaton/relaton-ietf/issues/52

**Comment by ronaldtse** [comment] 2021-12-28 09:39
@andrew2net in the BibXML Service we need to provide a `reference[@anchor]` that is dynamically generated from the requested file name due to legacy path handling.

The functionality of updating the anchor will be implemented in ietf-ribose/bibxml-service#57 and should not be necessary for Relaton-IETF. So let's remove it here?

**Comment by andrew2net** [comment] 2021-12-28 16:17
fixed in relaton-ietf -v 1.9.7

**Closed** 2021-12-28 22:13 UTC
